name: Update CSVs and upload to R2

on:
  schedule:
    # 04:45 UTC = 12:45 AM ET (daylight); safe window after GA's 11:34 PM ET draw
    - cron: '45 4 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    environment:
      name: r2-prod
    env:
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID || vars.CF_ACCOUNT_ID }}
      CF_API_TOKEN:  ${{ secrets.CF_API_TOKEN }}
      R2_BUCKET:     ${{ secrets.R2_BUCKET || vars.R2_BUCKET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify required secrets/vars are present
        run: |
          [ -z "$CF_ACCOUNT_ID" ] && echo "CF_ACCOUNT_ID is MISSING" && exit 1 || echo "CF_ACCOUNT_ID is set"
          [ -z "$CF_API_TOKEN" ]  && echo "CF_API_TOKEN is MISSING"  && exit 1 || echo "CF_API_TOKEN is set"
          [ -z "$R2_BUCKET" ]     && echo "R2_BUCKET is MISSING"     && exit 1 || echo "R2_BUCKET is set"

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run updater
        run: node scripts/update_csvs.mjs

      - name: Show local CSVs (before upload)
        run: |
          for f in public/data/multi/powerball.csv public/data/multi/megamillions.csv public/data/ga/cash4life.csv; do
            echo "---- $f ----"
            wc -l "$f" || true
            sed -n '1,5p' "$f" || true
          done

      - name: Wrangler version
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: --version

      - name: List R2 buckets
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: r2 bucket list

      # -------- Uploads --------

      - name: Upload Fantasy 5 to R2
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: r2 object put ${{ env.R2_BUCKET }}/ga/fantasy5.csv --file=public/data/ga/fantasy5.csv --content-type=text/csv --cache-control=public,max-age=3600,must-revalidate

      - name: Peek Fantasy 5 (full file to logs)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: r2 object get ${{ env.R2_BUCKET }}/ga/fantasy5.csv --pipe

      - name: Upload Cash4Life to R2
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: r2 object put ${{ env.R2_BUCKET }}/ga/cash4life.csv --file=public/data/ga/cash4life.csv --content-type=text/csv --cache-control=public,max-age=3600,must-revalidate

      - name: Peek Cash4Life (full file to logs)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: r2 object get ${{ env.R2_BUCKET }}/ga/cash4life.csv --pipe

      - name: Upload Powerball to R2
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: r2 object put ${{ env.R2_BUCKET }}/multi/powerball.csv --file=public/data/multi/powerball.csv --content-type=text/csv --cache-control=public,max-age=3600,must-revalidate

      - name: Peek Powerball (full file to logs)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: r2 object get ${{ env.R2_BUCKET }}/multi/powerball.csv --pipe

      - name: Upload Mega Millions to R2
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: r2 object put ${{ env.R2_BUCKET }}/multi/megamillions.csv --file=public/data/multi/megamillions.csv --content-type=text/csv --cache-control=public,max-age=3600,must-revalidate

      - name: Peek Mega Millions (full file to logs)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: r2 object get ${{ env.R2_BUCKET }}/multi/megamillions.csv --pipe

      # -------- Commit at the end (CSV-only, safe) --------
      - name: Commit CSV changes only (safe)
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

        
          git restore --worktree --staged package.json package-lock.json 2>/dev/null || true

           git add public/data/ga public/data/multi


          if git diff --cached --quiet; then
            echo "No CSV changes to commit."
            exit 0
          fi

          echo "Changes to commit:"
          git diff --cached --name-status

          git commit -m "chore: update CSVs"
          git push