name: Update CSVs and upload to R2

on:
  schedule:
    # 04:45 UTC = 12:45 AM ET (daylight); safe window after GA's 11:34 PM ET draw
    - cron: '45 4 * * *'
  workflow_dispatch: {}

permissions:
  contents: write  # allow commit back to repo if files changed

jobs:
  update:
    runs-on: ubuntu-latest
    environment:
      name: r2-prod
    # Hoist creds to the job env so every step (including actions) sees them.
    env:
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID || vars.CF_ACCOUNT_ID }}
      CF_API_TOKEN:  ${{ secrets.CF_API_TOKEN }}
      R2_BUCKET:     ${{ secrets.R2_BUCKET || vars.R2_BUCKET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Fail fast if any credential is missing (run this BEFORE using wrangler)
      - name: Verify required secrets/vars are present
        run: |
          [ -z "$CF_ACCOUNT_ID" ] && echo "CF_ACCOUNT_ID is MISSING" && exit 1 || echo "CF_ACCOUNT_ID is set"
          [ -z "$CF_API_TOKEN" ]  && echo "CF_API_TOKEN is MISSING"  && exit 1 || echo "CF_API_TOKEN is set"
          [ -z "$R2_BUCKET" ]     && echo "R2_BUCKET is MISSING"     && exit 1 || echo "R2_BUCKET is set"


      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run updater
        run: node scripts/update_csvs.mjs

      - name: Commit changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git pull --rebase || true
            git add public/data/ga/*.csv
            git commit -m "chore: update CSVs"
            git push
          else
            echo "No CSV changes to commit."
          fi
      - name: Wrangler version
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: --version

      # Optional: show what we're about to upload
      - name: Show Fantasy 5 CSV (before upload)
        run: |
          sed -n '1,20p' public/data/ga/fantasy5.csv || true
          wc -l public/data/ga/fantasy5.csv || true


      # Smoke test Wrangler auth + bucket visibility
      - name: List R2 buckets
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: r2 bucket list
    

      # ✅ # ✅ Upload Fantasy 5
      - name: Upload Fantasy 5 to R2
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: >
           r2 object put ${{ env.R2_BUCKET }}/ga/fantasy5.csv
           --file=public/data/ga/fantasy5.csv
            --content-type=text/csv
            --content-disposition=attachment;filename=fantasy5.csv
            --cache-control=public,max-age=3600,must-revalidate

      # ✅ Upload Cash4Life
      - name: Upload Cash4Life to R2
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: >
            r2 object put ${{ env.R2_BUCKET }}/ga/cash4life.csv
            --file=public/data/ga/cash4life.csv
            --content-type=text/csv
            --content-disposition=attachment;filename=cash4life.csv
            --cache-control=public,max-age=3600,must-revalidate

      # ✅ Upload Powerball
      - name: Upload Powerball to R2
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: >
           r2 object put ${{ env.R2_BUCKET }}/multi/powerball.csv
           --file=public/data/multi/powerball.csv
            --content-type=text/csv
            --content-disposition=attachment;filename=powerball.csv
            --cache-control=public,max-age=3600,must-revalidate

      # ✅ Upload Mega Millions
      - name: Upload Mega Millions to R2
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          command: >
           r2 object put ${{ env.R2_BUCKET }}/multi/megamillions.csv
           --file=public/data/multi/megamillions.csv
           --content-type=text/csv
           --content-disposition=attachment;filename=megamillions.csv
           --cache-control=public,max-age=3600,must-revalidate
